// Balloon — web-domain source list.
// Links pointing at these domains are highlighted inside posts on every
// supported platform. Categories reuse BALLOON_CATEGORIES from accounts.js.
// blocked: true → the post is hidden behind an overlay when
// "Block posts linking to bad sources" is enabled in the popup.

const BALLOON_SOURCES = [

  // ═══ RUSSIAN STATE MEDIA ══════════════════════════════════════════════════

  { domain: "rt.com", name: "RT", category: "state-propaganda", blocked: true, country: "RU",
    detail: "RT (Russia Today) is funded by the Russian federal budget. Broadcasting banned in the EU and UK since 2022.",
    source: "EU Reg. 2022/350 · Ofcom 2022" },
  { domain: "sputniknews.com", name: "Sputnik", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Owned by Rossiya Segodnya, a Russian state media holding. EU distribution suspended in 2022.",
    source: "EU Reg. 2022/350 · FARA" },
  { domain: "sputnikglobe.com", name: "Sputnik", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Current international domain of Sputnik (Rossiya Segodnya).",
    source: "EU Reg. 2022/350" },
  { domain: "ria.ru", name: "RIA Novosti", category: "state-propaganda", blocked: true, country: "RU",
    detail: "RIA Novosti is owned by Rossiya Segodnya, the Kremlin's international media holding.",
    source: "EU Reg. 2022/350" },
  { domain: "tass.com", name: "TASS", category: "state-propaganda", blocked: false, country: "RU",
    detail: "Russia's official state news agency, operating under a government charter.",
    source: "TASS Federal Charter" },
  { domain: "tass.ru", name: "TASS", category: "state-propaganda", blocked: false, country: "RU",
    detail: "Russian-language site of the TASS state news agency.",
    source: "TASS Federal Charter" },
  { domain: "ruptly.tv", name: "Ruptly", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Video agency and subsidiary of RT.",
    source: "EU Reg. 2022/879" },
  { domain: "redfish.media", name: "Redfish", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Video outlet run as part of the RT network.",
    source: "Twitter state-media label · EU DisinfoLab" },
  { domain: "strategic-culture.su", name: "Strategic Culture Foundation", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Online journal identified by the US State Department as directed by Russia's foreign intelligence service.",
    source: "US State Dept. GEC 2020" },
  { domain: "strategic-culture.org", name: "Strategic Culture Foundation", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Former domain of the Strategic Culture Foundation.",
    source: "US State Dept. GEC 2020" },
  { domain: "southfront.org", name: "SouthFront", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Military-analysis site described by the US State Department as part of Russia's disinformation ecosystem.",
    source: "US State Dept. GEC 2020" },
  { domain: "news-front.info", name: "NewsFront", category: "state-propaganda", blocked: true, country: "RU",
    detail: "Crimea-based outlet sanctioned for spreading Kremlin disinformation.",
    source: "US Treasury OFAC 2021" },
  { domain: "globalresearch.ca", name: "Global Research", category: "misinformation", blocked: true,
    detail: "Website of the Centre for Research on Globalization, identified as a proxy in Russia's disinformation ecosystem.",
    source: "US State Dept. GEC 2020" },

  // ═══ CHINESE STATE MEDIA ══════════════════════════════════════════════════

  { domain: "globaltimes.cn", name: "Global Times", category: "state-propaganda", blocked: false, country: "CN",
    detail: "Tabloid published by People's Daily, the official newspaper of the Chinese Communist Party.",
    source: "US State Dept. foreign mission designation 2020" },
  { domain: "cgtn.com", name: "CGTN", category: "state-propaganda", blocked: false, country: "CN",
    detail: "China Global Television Network — international arm of state broadcaster CCTV. UK licence revoked in 2021.",
    source: "Ofcom 2021" },
  { domain: "chinadaily.com.cn", name: "China Daily", category: "state-propaganda", blocked: false, country: "CN",
    detail: "English-language daily owned by the CCP Publicity Department.",
    source: "US State Dept. foreign mission designation 2020 · FARA" },
  { domain: "xinhuanet.com", name: "Xinhua", category: "state-propaganda", blocked: false, country: "CN",
    detail: "China's official state press agency, a ministry-level institution of the State Council.",
    source: "US State Dept. foreign mission designation 2020" },
  { domain: "news.cn", name: "Xinhua", category: "state-propaganda", blocked: false, country: "CN",
    detail: "Current domain of Xinhua, China's official state press agency.",
    source: "US State Dept. foreign mission designation 2020" },
  { domain: "people.cn", name: "People's Daily", category: "state-propaganda", blocked: false, country: "CN",
    detail: "Official newspaper of the Central Committee of the Chinese Communist Party.",
    source: "US State Dept. foreign mission designation 2020" },
  { domain: "cctv.com", name: "CCTV", category: "state-propaganda", blocked: false, country: "CN",
    detail: "China Central Television, the state broadcaster controlled by the CCP Publicity Department.",
    source: "RSF World Press Freedom Index" },

  // ═══ IRANIAN STATE MEDIA ══════════════════════════════════════════════════

  { domain: "presstv.ir", name: "Press TV", category: "state-propaganda", blocked: true, country: "IR",
    detail: "Owned by IRIB, which answers to Iran's Supreme Leader. Ofcom revoked its UK licence in 2012.",
    source: "Ofcom 2012 · US Treasury OFAC" },
  { domain: "presstv.com", name: "Press TV", category: "state-propaganda", blocked: true, country: "IR",
    detail: "Alternate domain of Iranian state broadcaster Press TV.",
    source: "US DOJ domain seizure 2021" },
  { domain: "hispantv.com", name: "HispanTV", category: "state-propaganda", blocked: true, country: "IR",
    detail: "Spanish-language channel of Iran's IRIB state broadcaster.",
    source: "US Treasury OFAC" },
  { domain: "tasnimnews.com", name: "Tasnim News", category: "state-propaganda", blocked: true, country: "IR",
    detail: "News agency affiliated with Iran's Islamic Revolutionary Guard Corps.",
    source: "US Treasury OFAC 2019" },
  { domain: "farsnews.ir", name: "Fars News", category: "state-propaganda", blocked: true, country: "IR",
    detail: "News agency affiliated with Iran's Islamic Revolutionary Guard Corps.",
    source: "US Treasury OFAC 2013" },
  { domain: "mehrnews.com", name: "Mehr News", category: "state-propaganda", blocked: false, country: "IR",
    detail: "Iranian news agency owned by the Islamic Development Organization, a state body.",
    source: "RSF" },
  { domain: "almayadeen.net", name: "Al Mayadeen", category: "state-propaganda", blocked: true, country: "LB",
    detail: "Beirut-based channel aligned with the Iran–Hezbollah axis.",
    source: "EU DisinfoLab" },

  // ═══ OTHER STATE MEDIA ════════════════════════════════════════════════════

  { domain: "kcna.kp", name: "KCNA", category: "state-propaganda", blocked: true, country: "KP",
    detail: "Korean Central News Agency, North Korea's sole state news agency.",
    source: "RSF World Press Freedom Index" },
  { domain: "telesurtv.net", name: "teleSUR", category: "state-funded", blocked: false, country: "VE",
    detail: "Caracas-based network majority-funded by the Venezuelan government.",
    source: "RSF" },
  { domain: "telesurenglish.net", name: "teleSUR English", category: "state-funded", blocked: false, country: "VE",
    detail: "English service of the Venezuelan state-funded network teleSUR.",
    source: "RSF" },
  { domain: "prensa-latina.cu", name: "Prensa Latina", category: "state-propaganda", blocked: false, country: "CU",
    detail: "Official news agency of the Cuban state.",
    source: "RSF World Press Freedom Index" },

  // ═══ LOW-CREDIBILITY / CONSPIRACY ═════════════════════════════════════════

  { domain: "infowars.com", name: "InfoWars", category: "misinformation", blocked: true,
    detail: "Conspiracy site run by Alex Jones, who was found liable for defamation over false Sandy Hook claims.",
    source: "Connecticut Superior Court 2022 · MBFC" },
  { domain: "naturalnews.com", name: "Natural News", category: "misinformation", blocked: true,
    detail: "Health-conspiracy site repeatedly removed from major platforms for spam and misinformation.",
    source: "MBFC · Facebook removal 2019" },
  { domain: "thegatewaypundit.com", name: "The Gateway Pundit", category: "misinformation", blocked: false,
    detail: "Partisan site with a long record of failed fact-checks, including false 2020 election claims.",
    source: "MBFC · NewsGuard" },
  { domain: "zerohedge.com", name: "ZeroHedge", category: "misinformation", blocked: false,
    detail: "Financial blog with a record of publishing conspiracy theories and unverified claims.",
    source: "MBFC · NewsGuard" },
  { domain: "beforeitsnews.com", name: "Before It's News", category: "misinformation", blocked: true,
    detail: "User-generated site that publishes unvetted conspiracy content.",
    source: "MBFC" },
  { domain: "newspunch.com", name: "News Punch", category: "misinformation", blocked: true,
    detail: "Formerly YourNewsWire; repeatedly publishes fabricated stories.",
    source: "MBFC · Snopes" },
  { domain: "yournewswire.com", name: "YourNewsWire", category: "misinformation", blocked: true,
    detail: "Former name of News Punch; widely documented fake-news publisher.",
    source: "MBFC · Snopes" },
  { domain: "thegrayzone.com", name: "The Grayzone", category: "misinformation", blocked: false,
    detail: "Outlet that frequently amplifies Russian, Chinese and Syrian state narratives.",
    source: "EU DisinfoLab · Bellingcat" },
  { domain: "mintpressnews.com", name: "MintPress News", category: "misinformation", blocked: false,
    detail: "Outlet with a record of amplifying state-aligned narratives and unverified conflict claims.",
    source: "MBFC" },
  { domain: "21stcenturywire.com", name: "21st Century Wire", category: "misinformation", blocked: true,
    detail: "Conspiracy site that has promoted false-flag claims about major news events.",
    source: "MBFC" },
  { domain: "veteranstoday.com", name: "Veterans Today", category: "misinformation", blocked: true,
    detail: "Conspiracy site identified as a platform for Russian state-linked content.",
    source: "US State Dept. GEC 2020" },
  { domain: "childrenshealthdefense.org", name: "Children's Health Defense", category: "misinformation", blocked: false,
    detail: "Anti-vaccine advocacy group identified as a major source of vaccine misinformation.",
    source: "CCDH 'Disinformation Dozen' 2021" },
  { domain: "mercola.com", name: "Mercola", category: "misinformation", blocked: false,
    detail: "Alternative-health site identified as a leading spreader of vaccine misinformation.",
    source: "CCDH 'Disinformation Dozen' 2021" },
  { domain: "expose-news.com", name: "The Exposé", category: "misinformation", blocked: true,
    detail: "UK site that repeatedly publishes debunked health and vaccine claims.",
    source: "Full Fact · Reuters Fact Check" },
  { domain: "theepochtimes.com", name: "The Epoch Times", category: "misinformation", blocked: false,
    detail: "Outlet with documented promotion of conspiracy theories and election misinformation.",
    source: "MBFC · NewsGuard" },
  { domain: "oann.com", name: "One America News", category: "misinformation", blocked: false,
    detail: "Cable network that settled defamation claims over false 2020 election fraud reporting.",
    source: "Smartmatic v. OAN settlement 2024 · MBFC" },

  // ═══ SATIRE / FABRICATED ══════════════════════════════════════════════════

  { domain: "worldnewsdailyreport.com", name: "World News Daily Report", category: "misinformation", blocked: true,
    detail: "Fabricated-news site whose stories are regularly shared as real. Disclaimer says content is fiction.",
    source: "Snopes · PolitiFact" },
  { domain: "theonion.com", name: "The Onion", category: "satire", blocked: false,
    detail: "Satirical publication. Content is intentionally fictional.",
    source: "The Onion, Inc." },
  { domain: "babylonbee.com", name: "The Babylon Bee", category: "satire", blocked: false,
    detail: "Conservative satirical site. Content is intentionally fictional.",
    source: "Snopes" }
];
